# Generated by Django 5.0.4 on 2025-02-25 15:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadMemoria',
            fields=[
                ('id_cantidad_memoria', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(unique=True, verbose_name='Cantidad (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('id_estado_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id_gerencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id_tipo_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMemoria',
            fields=[
                ('id_tipo_memoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
                ('gerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.gerencia', verbose_name='Gerencia')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaEspecifica',
            fields=[
                ('id_caracteristica_especifica', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_procesador', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de Procesador')),
                ('velocidad_red', models.CharField(blank=True, max_length=45, null=True, verbose_name='Velocidad de Red')),
                ('interfaz_conexion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Interfaz de Conexión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('cantidad_memoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.cantidadmemoria', verbose_name='Cantidad de Memoria')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.caracteristica', verbose_name='Característica')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.tipodispositivo', verbose_name='Tipo de Dispositivo')),
                ('tipo_memoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.tipomemoria', verbose_name='Tipo de Memoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclatura', models.CharField(max_length=45, unique=True, verbose_name='Nomenclatura')),
                ('serie', models.CharField(blank=True, max_length=45, null=True, verbose_name='Número de Serie')),
                ('jira', models.CharField(blank=True, max_length=45, null=True, verbose_name='Jira Ticket')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.tipodispositivo', verbose_name='Tipo de Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoCaracteristica',
            fields=[
                ('id_dispositivo_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=45, verbose_name='Valor')),
                ('caracteristica_especifica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.caracteristicaespecifica', verbose_name='Característica Específica')),
                ('dispositivo_id_dispositivo', models.ForeignKey(db_column='dispositivo_id_dispositivo', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo Característica',
                'verbose_name_plural': 'Dispositivos Características',
                'db_table': 'dispositivo_caracteristica',
            },
        ),
        migrations.CreateModel(
            name='DispositivoPropietarioHistorico',
            fields=[
                ('id_dispositivo_propietario_historico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(verbose_name='Fecha de Cambio')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_propietario_historico', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Propietario')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('propietario_id_anterior', models.ForeignKey(blank=True, db_column='propietario_id_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Propietario Anterior')),
                ('propietario_id_nuevo', models.ForeignKey(blank=True, db_column='propietario_id_nuevo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_nuevo', to=settings.AUTH_USER_MODEL, verbose_name='Propietario Nuevo')),
            ],
            options={
                'verbose_name': 'Dispositivo Propietario Histórico',
                'verbose_name_plural': 'Dispositivos Propietarios Históricos',
            },
        ),
        migrations.CreateModel(
            name='DispositivoEstado',
            fields=[
                ('id_dispositivo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentario')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_dispositivo', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Estado')),
                ('dispositivo_id_dispositivo', models.ForeignKey(db_column='dispositivo_id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('estado_id_estado', models.ForeignKey(db_column='estado_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.estadodispositivo', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Dispositivo Estado',
                'verbose_name_plural': 'Dispositivos Estados',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=45, verbose_name='Agencia')),
                ('piso', models.CharField(blank=True, max_length=45, null=True, verbose_name='Piso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'unique_together': {('agencia', 'piso')},
            },
        ),
        migrations.CreateModel(
            name='DispositivoUbicacion',
            fields=[
                ('id_dispositivo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentario')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_ubicacion_dispositivo', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Ubicación')),
                ('dispositivo_id_dispositivo', models.ForeignKey(db_column='dispositivo_id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('ubicacion_id_ubicacion', models.ForeignKey(db_column='ubicacion_id_ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Dispositivo Ubicación',
                'verbose_name_plural': 'Dispositivos Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('marca_id_marca', models.ForeignKey(db_column='marca_id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.marca', verbose_name='Marca')),
            ],
            options={
                'unique_together': {('nombre', 'marca_id_marca')},
            },
        ),
    ]
